### ISSUE TITLE
url好像不能用

### ISSUE THREAD

**Issue by anlijun** [kamikat/bilibili-playurl#1]
{
code: -404,
message: "结果为空或者已被删除"
}

**Comment by kamikat** [comment]
提供一下 URL？有些视频是要给 Cookie 才能看到的。

**Comment by anyouzy** [comment]
厉害厉害，vm-159和vm-160源码很难看懂。。。。能否提供未经过编译的代码供我学习啊，谢谢。

**Comment by kamikat** [comment]
那段是播放器代码的某一段
